name: Mise à jour CBBI Zones

on:
  schedule:
    - cron: '* * * * *'   # Toutes les minutes (tu pourras changer en '0 3 * * *' pour 3h du matin)
  workflow_dispatch:      # Permet d’exécuter manuellement

jobs:
  update-zones:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer le script cbbi-zone-detector.js
        run: node Btc/Fibo-zones/cbbi-zone-detector.js

      - name: Configurer git et push les changements
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout -B main
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Mise à jour auto des zones" || echo "Aucun changement à committer"
          git push https://x-access-token:${GH_TOKEN}@github.com/totopirate/cbbi-indicator.git HEAD:main
