name: Mise à jour CBBI Zones

on:
  schedule:
    - cron: '* * * * *'   # Toutes les minutes
  workflow_dispatch: # exécution manuelle

jobs:
  update-zones:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer le script
        run: node Btc/Fibo-zones/cbbi-zone-detector.js

      - name: Commit et push des changements
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Mise à jour auto des zones" || echo "Aucun changement"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
